name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at midnight UTC
  workflow_dispatch:       # allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: Sathwik-0906
          outputs: |
            dist/github-contribution-grid-snake-dark.svg

      - name: Create dist directory
        run: mkdir -p dist

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Recolor dots to green
        run: node scripts/colorize-dots.js

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
